// Collection names as constants
export const Collections = {
    USERS: 'users',
    PERMISSIONS: 'permissions',
    SCHOOLS: 'schools',
    TEACHERS: 'teachers',
    MENTORS: 'mentors',
    TRAINING_PROGRAMS: 'training_programs',
    TRAINING_ASSIGNMENTS: 'training_assignments',
    MENTOR_TRAINING_ASSIGNMENTS: 'mentor_training_assignments',
    SCHOOL_ASSIGNMENTS: 'school_assignments',
    TRAINING_ATTENDANCE: 'training_attendance',
    MENTOR_TRAINING_ATTENDANCE: 'mentor_training_attendance',
    CERTIFICATE_TEMPLATES: 'certificate_templates',
    USER_DEVICES: 'user_devices',
    CHAT_SESSIONS: 'chat_sessions',
    CHAT_MESSAGES: 'chat_messages',
    EMPLOYEE_TASKS: 'employee_tasks',
    SCHOOL_FOLLOWUPS: 'school_followups',
    SCHOOL_QUERIES: 'school_queries',
    EVENTS: 'events',
    STUDENTS: 'students',
    STUDENT_ASSESSMENTS: 'student_assessments',
    MANAGEMENT: 'management',
    ADMIN_PERSONNEL: 'admin_personnel',
    MOM_NOTES: 'mom_notes',
    TRAINING_SESSIONS: 'training_sessions',
    YOUTUBE_VIDEOS: 'youtube_videos',
} as const;
